 
language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: 7ca71881-ec95-4d6e-8944-dd195d953905
  app: sentinellog
  on:
    branch: master