language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: z3LmzKs0LfnPmWVjWmwmvyCqB7Jp8r3QUi7M5wKb2X6Lw7L0wzHWt20xgC27XQcXQChWE8lvvpqvSMg6gRS7mdIJWcM/KHBj5YfT1udKzv9Pa83TeEDjkQ+lNdhoQekXZ4NR47oWSXtpi+gTLysPBATh6aKlmXH/5XKKHfspQpnyNRQwMkw4WVG9iHstOelPMgvNa5Eq8j2AccjJ/ju2l8QLYwAk8Ou3TrOycRMzwqPUuM8evv/CCcg1DM8HbKamEnzK00Kb0uSEfhMNG4ZPbFGQ8WwclUFijfQnyZ8nPjftgMaOODuH0isC0Uop0Y7zeW+7IR/turnGW98FCK2ChVA3orjdfDiJO9GvsyMn0XdsC2muhIHKonUgDGSj5CLuZ8zofKydv5U5wDsVPkLAcTNVLX8YIAJZDnqft/WeG9mr6Lz1Ft5R9RI7NwBrEu0AuyiU0G6Jvd/QqERVJjCTxskOQMJbL/cLEaUmPbO44z/2evjDyW2CDKfyc1tB4PYKwGcDC2Qn+DzyM1XZEY25AgTCe9z531egiyjMlp/KIRGuW+sCfqC5FJay9OUC/iigVySkkrTFNu8cZvoFrMZGiwq8hZh64xnlCMAmg+f9/FIE8yLcFq4T2wAXFZh9Ei2rcIEmJzNqSSJFitNGGC3hvm7s/e5aOJhE9VzVcfIQdv4=
  app: sentinellog
  on:
    repo: batistasamuel/travis_heroku
