 
language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: 82f3544b-35b9-4d66-9c07-d2f13122fff4
  app: sentinellog
  on:
    repo: batistasamuel/travis_heroku