 
language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: aa1113be-57f9-4c13-8622-4b0e788b1b2e
  app: sentinellog
  on:
    branch: master